/**
 * SecScan target profile — the scanner webapp (https://secscan.us).
 *
 * EXHAUSTIVE battery (v0.7.0): surface × technique. Every distinct attacker
 * intent against the real surface is one item. Surfaces: scan intake
 * (URL field + options), SSRF guard, DNS TXT ownership gate, scan
 * lifecycle, scan listing, report view/export, share links, AI opt-out,
 * rate limits, auth/session, API surface, TLS/headers/CORS, error
 * handlers, scanner-efficacy canaries, cross-cutting.
 *
 * Non-destructive always: never trigger emails to real users, never delete
 * scans/reports, benign canary content only, races are single paired
 * requests. Items needing setup say so in `needs` — honestly.
 */

import type { TargetBatteryItem, TargetProfile } from "./types.js";

const SECSCAN_BATTERY: TargetBatteryItem[] = [
  // ============================================ INTAKE URL FIELD (validation)
  {
    id: "SS-001", category: "validation", name: "Intake URL type juggling",
    brief: "Non-string types in the url field — does anything but a string ever reach the SSRF guard?",
    owasp: "WSTG-INPV-01", attackId: "T1190",
    what: "Submit the intake url field as an array, object, boolean, and number instead of a string. Observe coercion: does the validator reject, stringify, or pass a non-string downstream where the SSRF guard might mishandle it?",
  },
  {
    id: "SS-002", category: "validation", name: "Intake URL scheme allowlist",
    brief: "Dangerous schemes (javascript:, data:, file:, gopher:, dict:, ftp:) — allowlist or blocklist?",
    owasp: "WSTG-INPV-01", attackId: "T1190",
    what: "Submit intake URLs with schemes javascript:, data:, file:, gopher:, dict:, ftp:, and jar:. Record exactly which are rejected vs accepted — a blocklist that misses one scheme is the finding. Never submit a scheme that would execute locally.",
  },
  {
    id: "SS-003", category: "validation", name: "Intake URL userinfo trick",
    brief: "https://secscan.us@evil-canary — does the validator see the real host?",
    owasp: "WSTG-INPV-01", attackId: "T1190",
    what: "Submit https://secscan.us@<canary-host> and https://user:pass@<canary-host> as the intake URL. If the validator or the SSRF guard parses the host as secscan.us while the fetch goes to the canary host, that divergence is the finding. Canary hosts only.",
  },
  {
    id: "SS-004", category: "validation", name: "Double-encoded intake URL",
    brief: "Double-encoded hosts and paths — is validation pre- or post-decode?",
    owasp: "WSTG-INPV-01", attackId: "T1027",
    what: "Submit double-encoded URLs (%252e, %25 encoding of the host). Determine whether the intake validator normalizes before or after checking, and whether the SSRF guard sees the same normalized form.",
  },
  {
    id: "SS-005", category: "validation", name: "Unicode / IDN homograph domain",
    brief: "Lookalike unicode domains — does the validator normalize to punycode before checking?",
    owasp: "WSTG-INPV-01", attackId: "T1027",
    what: "Submit IDN homographs of secscan.us (cyrillic/greek lookalikes) as the intake target. Observe whether validation punycode-normalizes before the ownership/allow checks. Benign canary domains only.",
  },
  {
    id: "SS-006", category: "validation", name: "Overlong intake URL",
    brief: "Max-length URLs — truncation, rejection, or silent acceptance?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit URLs at and beyond plausible length limits (2k, 8k, 64k chars). Observe: clean rejection, silent truncation (dangerous — what got truncated?), or acceptance. Never a flood — a handful of single requests.",
  },
  {
    id: "SS-007", category: "validation", name: "Null byte and control chars in URL",
    brief: "Embedded nulls and control characters — stripped, rejected, or passed to the fetcher?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit intake URLs containing %00, %0d, %0a, and raw control characters. Observe whether the validator strips, rejects, or passes them to the SSRF guard / fetcher, where a null byte could truncate a host check.",
  },
  {
    id: "SS-008", category: "validation", name: "Port smuggling in intake URL",
    brief: "Explicit :443, :0, :65536, :80 on https — does the port survive validation intact?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit the intake URL with explicit ports: :443, :80 on an https URL, :0, :65536 (invalid), and :22. Observe whether validation preserves, strips, or rejects the port — and whether the guard checks the same host:port the fetcher uses.",
  },
  {
    id: "SS-009", category: "validation", name: "Scheme/host case tricks",
    brief: "HtTpS://SEcScAn.Us — is normalization case-consistent end to end?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit mixed-case scheme and host. The question is consistency: if the validator lowercases but the guard compares raw (or vice versa), case becomes a bypass primitive.",
  },
  {
    id: "SS-010", category: "validation", name: "CRLF injection in URL field",
    brief: "Embedded CRLF — header injection or clean rejection?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit intake URLs containing %0d%0a followed by benign header-shaped text. Observe whether the validator rejects or the value flows into any header-building path. Benign content only; the injection attempt itself is the test.",
  },
  {
    id: "SS-011", category: "validation", name: "Regex bypass on domain validator",
    brief: "Unanchored patterns, newline tricks — can the domain regex be walked around?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Probe the intake domain/URL regex with classic bypasses: secscan.us.evil-canary, evilsecscan.us, newline-embedded domains, and subdomain-boundary tricks. Single probes — never ReDoS-shaped input.",
  },
  {
    id: "SS-012", category: "validation", name: "DNS-rebinding-shaped hostname",
    brief: "Rebinding-shaped hostnames at the validator — flagged or accepted?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit hostnames shaped for DNS rebinding (short-TTL, dual-record canary hostnames) to the intake validator and observe the verdict. This tests the validator only — no actual rebinding attack is performed.",
    needs: "Canary DNS infrastructure under operator control.",
  },
  {
    id: "SS-013", category: "validation", name: "Loopback spellings at the validator",
    brief: "127.1, 2130706433, [::], 0.0.0.0 — does the validator catch every loopback spelling?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit decimal (2130706433), octal, short-form (127.1), IPv6 ([::1], [::]), and 0.0.0.0 loopback spellings. Validator-level verdicts only — these are never fetched. Any spelling the validator accepts is the finding.",
  },
  {
    id: "SS-014", category: "validation", name: "Private-range literals at the validator",
    brief: "10/8, 172.16/12, 192.168/16 in decimal/octal/hex — full private-range coverage?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit private-range IPs in dotted, decimal, octal, and hex spellings. Validator verdicts only, never fetched. Map exactly which spellings are caught — one missed spelling is the finding.",
  },
  {
    id: "SS-015", category: "validation", name: "Metadata-shaped addresses at the validator",
    brief: "169.254.169.254 and metadata spellings — rejected on sight?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit cloud-metadata-shaped addresses (169.254.169.254 and decimal/octal spellings) to the intake validator. Verdicts only — nothing is ever requested. A validator that accepts these is a critical finding.",
  },
  // ================================================= SSRF GUARD (logic)
  {
    id: "SS-016", category: "logic", name: "SSRF guard: redirect chain http→https→http",
    brief: "Multi-hop redirect chain through a canary redirector — every hop revalidated?",
    owasp: "WSTG-BUSL / SSRF", attackId: "T1190",
    what: "Submit an intake URL pointing at an operator-controlled redirector that chains http→https→http across 3 hops. Observe whether the per-hop revalidation fires on every hop or only the first. Benign canary targets only.",
    needs: "Canary redirector infrastructure under operator control.",
    blackNote: "One chain; the guard's behavior is the observation, not a bypass campaign.",
  },
  {
    id: "SS-017", category: "logic", name: "SSRF guard: redirect to private range via open-redirector hop",
    brief: "Canary open redirector pointing at a private-range-shaped host — does the guard catch the landing?",
    owasp: "WSTG-BUSL / SSRF", attackId: "T1190",
    what: "Chain: public canary URL → open redirector → private-range-shaped hostname (a canary name that RESOLVES to nothing routable, testing the guard's verdict, not an actual internal fetch). The guard must refuse the landing. Never a real internal address.",
    needs: "Canary redirector infrastructure under operator control.",
  },
  {
    id: "SS-018", category: "logic", name: "SSRF guard: per-hop revalidation depth",
    brief: "5-hop chain — is hop 5 checked as strictly as hop 1?",
    owasp: "WSTG-BUSL / SSRF", attackId: "T1190",
    what: "Submit a 5-hop canary redirect chain and determine the revalidation depth: does the guard check every hop, or does scrutiny decay after N hops? Benign canary targets only.",
    needs: "Canary redirector infrastructure under operator control.",
  },
  {
    id: "SS-019", category: "logic", name: "SSRF guard: redirect loop and max-redirect behavior",
    brief: "Redirect loops and 20-hop chains — sane termination or resource burn?",
    owasp: "WSTG-BUSL / SSRF", attackId: "T1190",
    what: "Submit a canary URL that redirects in a loop and one with a 20-hop chain. Observe max-redirect handling and whether loop detection terminates cleanly. Canary targets only; never a loop designed to burn scanner resources.",
  },
  {
    id: "SS-020", category: "logic", name: "SSRF guard: scheme downgrade mid-chain",
    brief: "https→http downgrade on hop 2 — does the guard re-evaluate the scheme?",
    owasp: "WSTG-BUSL / SSRF", attackId: "T1190",
    what: "Chain a canary https URL to an http URL mid-redirect. Observe whether the guard re-evaluates scheme policy per hop or inherits the first hop's approval. Canary targets only.",
    needs: "Canary redirector infrastructure under operator control.",
  },
  {
    id: "SS-021", category: "logic", name: "SSRF guard: host swap mid-chain",
    brief: "Hop 1 benign, hop 2 a canary evil host — is the new host fully re-vetted?",
    owasp: "WSTG-BUSL / SSRF", attackId: "T1190",
    what: "Redirect from a benign canary host to a different canary host mid-chain. The guard must treat the new host as a fresh target: full validation, not inherited trust. Canary targets only.",
    needs: "Canary redirector infrastructure under operator control.",
  },
  {
    id: "SS-022", category: "logic", name: "SSRF guard: DNS TTL games",
    brief: "Short-TTL canary DNS flipping between benign and blocked — validate-then-fetch race?",
    owasp: "WSTG-BUSL / SSRF", attackId: "T1190",
    what: "Point intake at a canary hostname whose DNS flips between a benign and a blocked answer on short TTL. This tests for a time-of-check/time-of-use gap between guard validation and fetch. Benign canary DNS only; single attempts, never a hammering loop.",
    needs: "Canary DNS infrastructure under operator control.",
    blackNote: "Single attempt; a TOCTOU gap is reported, not exploited repeatedly.",
  },
  {
    id: "SS-023", category: "logic", name: "Validator vs guard divergence",
    brief: "Same hostile URL through validator and guard separately — divergent verdicts?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit the same hostile-shaped canary URL and compare the intake validator's verdict against the SSRF guard's verdict independently. Any input one accepts and the other rejects is a seam worth naming in the report.",
  },
  // ============================================ INTAKE OPTIONS (mixed)
  {
    id: "SS-024", category: "functionality", name: "Mass assignment on scan options",
    brief: "role/isAdmin/userId/credits/tier flags smuggled into the intake JSON — do they bind?",
    owasp: "OWASP API3:2023", attackId: "T1190",
    what: "Add unexpected fields to the scan-intake JSON body: role, isAdmin, userId, credits, tier, aggressive. Observe whether they bind, validate, or are ignored — especially anything that could escalate the scan tier without authorization. Own test account only.",
  },
  {
    id: "SS-025", category: "functionality", name: "Hidden intake parameters",
    brief: "debug/preview/aggressive/callback/_method — undocumented params honored?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Probe the intake endpoint for undocumented parameters: debug, preview, aggressive, callback, _method, admin. Prefer parameters hinted at in client bundles over blind guessing — one probe per family.",
    blackNote: "Prefer parameters already hinted at in client code over blind guessing.",
  },
  {
    id: "SS-026", category: "logic", name: "Aggressive-tier escalation without authorization",
    brief: "Free-tier account requesting aggressive scans — enforced server-side?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "From a free-tier test account, request aggressive-tier scans via the intake API (tier flags, hidden params, direct endpoint). The server must refuse — a granted aggressive scan is the finding. Never consume someone else's quota.",
  },
  {
    id: "SS-027", category: "logic", name: "Negative/zero numeric scan options",
    brief: "wait_seconds=-1, limit=0 — validated, clamped, or computed on?",
    owasp: "WSTG-BUSL-01", attackId: "T1190",
    what: "Submit negative, zero, and absurd values for numeric intake options (wait_seconds, limit, depth). Observe whether the app validates, clamps, or computes on them — a negative wait becoming a huge one is the finding.",
  },
  {
    id: "SS-028", category: "functionality", name: "Content-type confusion on intake",
    brief: "Same payload as JSON, form, and text — identical parsing, validation, guard?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit the identical scan-intake payload as application/json, application/x-www-form-urlencoded, and text/plain. Observe whether parsing, validation, and the SSRF guard behave identically across content types.",
  },
  {
    id: "SS-029", category: "functionality", name: "HTTP method tampering on intake",
    brief: "Scan intake via GET/PUT/DELETE/X-HTTP-Method-Override — honored or rejected?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Replay the intake request as GET (params in query), PUT, DELETE, and POST with X-HTTP-Method-Override. A state-changing intake honored on GET is the finding. Own test account only.",
  },
  {
    id: "SS-030", category: "validation", name: "Parameter pollution on intake url",
    brief: "Duplicate url params — first wins, last wins, or array?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit duplicate url parameters (benign + hostile-shaped canary) in query and body. Observe which value wins and whether validator and guard agree on the winner.",
  },
  // ============================================ DNS OWNERSHIP GATE (mixed)
  {
    id: "SS-031", category: "logic", name: "DNS gate: wrong TXT value fails closed",
    brief: "Incorrect challenge TXT — clean failure, no partial verification?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Place a wrong value in the _secscan-challenge TXT record of an operator-controlled domain and trigger verification. The gate must fail closed with no partial-verified state. Operator-controlled domains only.",
    needs: "Operator-controlled test domain with DNS access.",
  },
  {
    id: "SS-032", category: "logic", name: "DNS gate: TXT on parent vs exact host",
    brief: "Challenge TXT on the parent domain — accepted for a subdomain claim?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Place the challenge TXT on the parent domain while claiming a subdomain (and vice versa). The gate must require the exact _secscan-challenge.<claimed-host> name — parental acceptance is the finding.",
    needs: "Operator-controlled test domain with DNS access.",
  },
  {
    id: "SS-033", category: "logic", name: "DNS gate: challenge hostname case/encoding tricks",
    brief: "Case and encoding variants of _secscan-challenge — exact-match enforced?",
    owasp: "WSTG-ATHZ-04", attackId: "T1027",
    what: "Probe whether the gate's challenge-hostname comparison is exact: case variants, punycode variants, and trailing-dot forms of _secscan-challenge.<domain>. Any accepted variant is the finding.",
    needs: "Operator-controlled test domain with DNS access.",
  },
  {
    id: "SS-034", category: "logic", name: "DNS gate: cross-domain challenge replay",
    brief: "Challenge issued for domain A replayed against domain B — bound to the domain?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Take a challenge token issued for one operator-controlled domain and present it during another domain's verification. Challenges must be domain-bound — cross-acceptance is the finding.",
    needs: "Two operator-controlled test domains with DNS access.",
  },
  {
    id: "SS-035", category: "logic", name: "DNS gate: verification polling without TXT",
    brief: "Poll the verification status with no TXT ever placed — any path to verified?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Trigger verification for an operator-controlled domain with no TXT record placed, then poll the status endpoint aggressively-but-politely for transitions. Any unverified→verified transition without the TXT is a critical finding.",
    needs: "Operator-controlled test domain with DNS access.",
    blackNote: "Single verification attempt; a gate that holds is a strong-defense finding.",
  },
  {
    id: "SS-036", category: "logic", name: "DNS gate: re-verification after TXT removal",
    brief: "TXT removed post-verification — does the verified status expire or persist forever?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Verify an operator-controlled domain, remove the TXT record, then observe whether the verified status persists indefinitely or lapses. Permanent verification after de-provisioning is the finding.",
    needs: "Operator-controlled test domain with DNS access.",
  },
  {
    id: "SS-037", category: "logic", name: "DNS gate: verification race vs TXT propagation",
    brief: "Single paired verify-now/verify-later around TXT placement — TOCTOU in the checker?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Fire a single pair of verification requests around TXT placement/removal timing and compare outcomes. One pair, one observation — testing for a time-of-check gap, never a hammering loop.",
    needs: "Operator-controlled test domain with DNS access.",
  },
  {
    id: "SS-038", category: "validation", name: "DNS gate: domain field validation",
    brief: "Trailing dots, encoding, overlong domains in the claimed domain — normalized exactly?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit claimed domains with trailing dots, mixed case, punycode, and overlong labels to the verification flow. Observe whether the claimed domain is normalized identically at challenge issuance and at TXT lookup.",
  },
  {
    id: "SS-039", category: "functionality", name: "DNS gate: verification-status enumeration oracle",
    brief: "verified vs unverified vs unknown domains — response differentials?",
    owasp: "WSTG-ATHN", attackId: "T1087",
    what: "Compare verification-status responses for verified, unverified, and nonexistent domains (own test domains). A differential that reveals another party's verification state is the finding — stop at the differential, never harvest.",
    needs: "Operator-controlled test domain with DNS access.",
    blackNote: "Minimal probes; stop at the first differential.",
  },
  {
    id: "SS-040", category: "logic", name: "DNS gate: stale challenge reuse",
    brief: "Old challenge token reused in a fresh verification — single-use enforced?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Complete one verification, then attempt a second verification reusing the first challenge token. Challenges must be single-use — replay acceptance is the finding.",
    needs: "Operator-controlled test domain with DNS access.",
  },
  // ============================================ SCAN LIFECYCLE (mixed)
  {
    id: "SS-041", category: "logic", name: "Report fetch for queued scan",
    brief: "Request the report before the scan runs — invalid lifecycle transition?",
    owasp: "WSTG-BUSL-06", attackId: "T1190",
    what: "Immediately after intake, request the report/export endpoints for the still-queued scan. Observe whether the app enforces queued→running→complete ordering or leaks partial state.",
  },
  {
    id: "SS-042", category: "logic", name: "Duplicate intake mid-run",
    brief: "Same URL resubmitted while its scan runs — deduped, double-charged, or double-run?",
    owasp: "WSTG-BUSL-04", attackId: "T1190",
    what: "Resubmit the identical intake while the first scan is still running. Observe: deduplicated, run twice, or charged twice. Own test account only; the observation is the finding.",
  },
  {
    id: "SS-043", category: "logic", name: "Credit deduction exactly once",
    brief: "Single paired intake — is the credit deducted exactly once?",
    owasp: "WSTG-BUSL-01", attackId: "T1190",
    what: "Fire a single pair of near-simultaneous intake requests and compare credit deduction: exactly one deduction expected. One pair, one observation — never engineered into a real double-spend.",
    blackNote: "Only against own test account with operator-owned credits.",
  },
  {
    id: "SS-044", category: "logic", name: "Cancel another account's scan",
    brief: "Cancel/abort endpoint aimed at another account's scan_id — authorized?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "If a cancel/abort affordance exists, aim it at another owned test account's scan. Cross-account cancellation is the finding — stop and report instantly. Never cancel anything not owned by the operator.",
    needs: "Second test account owned by the operator.",
  },
  {
    id: "SS-045", category: "validation", name: "Malformed scan_id shapes",
    brief: "Truncated/extended/non-hex scan_ids — strict UUID validation?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Request status/report with truncated, extended, non-hex, and brace-wrapped UUID shapes. Observe strictness — and whether any malformed shape produces a verbose error (see SS-057).",
  },
  {
    id: "SS-046", category: "functionality", name: "Status polling method tampering",
    brief: "Scan status via POST/PUT/DELETE — read endpoints that execute on write methods?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Replay the scan-status endpoint as POST, PUT, and DELETE. A read endpoint that changes state or behaves differently on write methods is the finding.",
  },
  {
    id: "SS-047", category: "validation", name: "Injection-shaped scan_id",
    brief: "SQLi/XSS-shaped scan_ids — parameterized, or verbose errors?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit benign injection-shaped strings as scan_id (quote marks, comment sequences, script tags). Observation only: parameterized handling vs verbose errors vs reflection. Never destructive payloads.",
  },
  {
    id: "SS-048", category: "logic", name: "Scan retry / re-run logic",
    brief: "Re-running a completed scan — charged again? state clean?",
    owasp: "WSTG-BUSL-06", attackId: "T1190",
    what: "Re-run a completed own-account scan via any retry affordance. Observe credit charging, whether the old report is replaced or versioned, and whether retry of a failed scan bypasses any gate.",
  },
  // ============================================ SCAN LISTING (mixed)
  {
    id: "SS-049", category: "functionality", name: "Listing pagination abuse",
    brief: "Negative/zero offsets, huge limits on the scan list — clamped or honored?",
    owasp: "WSTG-BUSL-01", attackId: "T1190",
    what: "Request the scan-listing endpoint with negative/zero offsets, huge limits, and non-numeric page values. Observe clamping — and watch for any other-account data in oversized responses (critical: stop and report instantly).",
  },
  {
    id: "SS-050", category: "functionality", name: "Listing sort/filter field abuse",
    brief: "Sort on non-indexed fields, filter injection — strict allowlist?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Sort and filter the scan list on non-indexed and nonexistent fields; try filter-operator injection (gt/lt/regex shapes). Observe whether field names are allowlisted and whether errors leak schema.",
  },
  {
    id: "SS-051", category: "logic", name: "Cross-account listing IDOR",
    brief: "Another account's scans in my list — the critical boundary test.",
    owasp: "OWASP API1:2023", attackId: "T1190",
    what: "With account A's session, manipulate listing parameters looking for account B's scans. Any cross-account data is a critical finding — stop and report instantly, never enumerate further.",
    needs: "Second test account owned by the operator.",
  },
  {
    id: "SS-052", category: "validation", name: "Listing limit clamping and type juggling",
    brief: "limit=array, limit=-1, limit=999999 — validated or computed on?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Type-juggle the listing limit/page parameters (arrays, strings, negatives, absurd values). Observe validation vs clamping — a negative limit that returns everything is the finding.",
  },
  // ============================================ REPORT VIEW (mixed)
  {
    id: "SS-053", category: "logic", name: "Cross-account report IDOR",
    brief: "Account B's report URL with account A's session — the authorization boundary.",
    owasp: "OWASP API1:2023", attackId: "T1190",
    what: "With account A's session, request account B's report URL directly. This is authorization-boundary testing between two owned test accounts — not UUID guessing (infeasible, never attempted). Two observations before a verdict: the anomalous response AND a control.",
    needs: "Second test account owned by the operator.",
  },
  {
    id: "SS-054", category: "functionality", name: "Method tampering on report fetch",
    brief: "Report via POST/PUT/DELETE — read endpoint honoring write methods?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Fetch a report as POST, PUT, DELETE, and PATCH. Note which methods the app honors vs rejects — a GET-only report that renders on POST is the finding.",
  },
  {
    id: "SS-055", category: "validation", name: "Malformed report_id shapes",
    brief: "Truncated/extended report_ids — strict validation or verbose errors?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Request reports with malformed ID shapes. Observe strictness and feed any verbose errors into the oracle analysis (SS-058).",
  },
  {
    id: "SS-056", category: "functionality", name: "Hidden report format parameters",
    brief: "format=json|pdf|html, download, print — undocumented render paths?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Probe the report endpoint for format/render parameters: format, download, print, raw, embed. Each undocumented path is new attack surface — test it for the same flaws as the main path.",
  },
  {
    id: "SS-057", category: "logic", name: "Report for failed scan",
    brief: "Failed scan's report page — error disclosure or clean state?",
    owasp: "WSTG-ERRH-01", attackId: "T1190",
    what: "Drive a scan to failure (invalid canary target) and inspect the report path: verbose failure reasons, internal hostnames, or stack traces leaking through the failure state.",
  },
  {
    id: "SS-058", category: "validation", name: "'No such scan' vs 'not your scan' differential",
    brief: "Error-message oracle on report access — existence vs authorization distinguished?",
    owasp: "WSTG-ERRH-01", attackId: "T1592.002",
    what: "Compare responses for: nonexistent scan ID, another account's scan ID (with two owned accounts), and malformed ID. Any differential between 'does not exist' and 'not yours' is an existence oracle — the finding, not a harvest.",
    needs: "Second test account owned by the operator.",
    blackNote: "Minimal probes; stop at the first differential.",
  },
  {
    id: "SS-059", category: "functionality", name: "Self-XSS via own scan data in report",
    brief: "Benign marker in canary target — reflected unescaped in my own report?",
    owasp: "WSTG-INPV-02", attackId: "T1190",
    what: "Scan a canary target containing a benign inert marker string and check whether it renders unescaped in the report HTML. Own account only, inert marker, no script execution pursued beyond the reflection observation.",
    needs: "Canary target under operator control.",
  },
  {
    id: "SS-060", category: "validation", name: "Report caching and stale authorization",
    brief: "Cached report served after access revoked — authorization re-checked?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Access a report, then change the authorization state (share revoked / session ended) and re-request. A cached copy served past revocation is the finding.",
  },
  // ============================================ REPORT EXPORT (mixed)
  {
    id: "SS-061", category: "functionality", name: "Path traversal in export filename",
    brief: "filename=../../x on report export — traversal or sanitized?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Tamper with any filename parameter on report export (filename=../../canary, encoded variants). Observe sanitization — the finding is whether user input reaches a filesystem path unsanitized. Benign canary names only.",
  },
  {
    id: "SS-062", category: "functionality", name: "Export content-type mismatch",
    brief: "JSON labeled as PDF and vice versa — content sniffing risk?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Request each export format and compare the Content-Type header against the actual bytes, plus X-Content-Type-Options presence. A mismatch that enables sniffing is the finding.",
  },
  {
    id: "SS-063", category: "validation", name: "Export format parameter injection",
    brief: "format=../../etc/passwd-shaped — validated against an allowlist?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit traversal-shaped and template-shaped format values. Observation only: allowlist validation vs verbose errors vs reflection. Never a real filesystem target.",
  },
  {
    id: "SS-064", category: "logic", name: "Export another account's report via direct URL",
    brief: "Direct export URL with another account's session — same boundary as view?",
    owasp: "OWASP API1:2023", attackId: "T1190",
    what: "Replay the export endpoints against another owned test account's report. Export paths sometimes skip the checks the view path enforces — that asymmetry is the finding.",
    needs: "Second test account owned by the operator.",
  },
  {
    id: "SS-065", category: "functionality", name: "Export of partial/running scan",
    brief: "Export mid-scan — partial data, errors, or clean refusal?",
    owasp: "WSTG-BUSL-06", attackId: "T1190",
    what: "Request exports while the scan is still running. Observe whether partial findings leak, the export errors cleanly, or a corrupt document is produced.",
  },
  // ============================================ SHARE LINKS (mixed)
  {
    id: "SS-066", category: "logic", name: "Share creation authorization",
    brief: "Share link for a scan I don't own — creation-side authz?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Attempt share-link creation for another owned test account's scan ID. Creation must require ownership — a share minted for someone else's scan is the finding.",
    needs: "Second test account owned by the operator.",
  },
  {
    id: "SS-067", category: "logic", name: "Expired share link access",
    brief: "Link past its 30-day expiry — dead, or still serving?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Create a share with the shortest allowed expiry, let it lapse (or manipulate the clock-facing parameter if the API exposes one), then request it. Any serving past expiry is the finding.",
  },
  {
    id: "SS-068", category: "functionality", name: "Share token tampering",
    brief: "Truncated/extended/re-encoded tokens — strict validation or prefix-tolerant?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Tamper with own share tokens: truncation, extension, base64 re-encoding, character swaps. Observe whether validation is strict or prefix-tolerant — tolerance is the finding.",
  },
  {
    id: "SS-069", category: "functionality", name: "Cross-share token swap",
    brief: "Token from share A on share B's URL — bound to the share?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Swap tokens between two own-account shares. Tokens must be bound to their share — cross-acceptance is the finding. Own account only.",
  },
  {
    id: "SS-070", category: "logic", name: "Token replay after revoke/expiry change",
    brief: "Revoked share's token replayed — single-use lifecycle enforced?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Revoke a share (or shorten its expiry to the past), then replay the old token. Revocation must actually kill the token — a replay that still serves is the finding.",
  },
  {
    id: "SS-071", category: "validation", name: "Share token entropy and format analysis",
    brief: "Token structure analyzed — entropy, predictability, information leakage?",
    owasp: "WSTG-ATHZ", attackId: "T1592.002",
    what: "Analyze own share tokens passively: length, alphabet, visible structure (embedded IDs? timestamps?). The analysis is observational — no brute-forcing, which is infeasible by design.",
  },
  {
    id: "SS-072", category: "logic", name: "Share of failed/partial scan",
    brief: "Sharing a failed scan — error internals exposed to anonymous viewers?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Create a share for a failed scan and inspect what an unauthenticated viewer sees: failure reasons and internal details must not leak wider than the authenticated report view.",
  },
  {
    id: "SS-073", category: "functionality", name: "Share-create method tampering and mass assignment",
    brief: "Share via GET/PUT, expiry smuggled in JSON — honored?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Create shares via GET/PUT/DELETE and smuggle expiry days, scope flags, and permission fields into the creation JSON. Observe method enforcement and field binding. Own account only.",
  },
  {
    id: "SS-074", category: "logic", name: "Absurd share expiry values",
    brief: "expiry=99999, 0, -1 — validated, clamped, or honored?",
    owasp: "WSTG-BUSL-01", attackId: "T1190",
    what: "Submit absurd expiry values (0, -1, 999999, non-numeric). Observe validation vs clamping — a negative expiry that means 'never expires' is the finding.",
  },
  {
    id: "SS-075", category: "validation", name: "Share token case/encoding in URL",
    brief: "Case-flipped and URL-encoded tokens — canonicalized before lookup?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Request own share URLs with case-flipped, URL-encoded, and double-encoded tokens. Observe canonicalization — inconsistent handling between creation-time and lookup-time is the finding.",
  },
  {
    id: "SS-076", category: "functionality", name: "Share viewer surface enumeration",
    brief: "What can an anonymous share viewer reach beyond the report?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "As an unauthenticated viewer of an own-account share, probe adjacent paths: API endpoints, other formats, directory traversal out of the share scope. The share must be a sealed room — any exit is the finding.",
  },
  // ============================================ AI OPT-OUT (mixed)
  {
    id: "SS-077", category: "logic", name: "Opt-out toggle persistence",
    brief: "AI opt-out — persisted per scan and per account, or cosmetic?",
    owasp: "WSTG-ATHZ / privacy", attackId: "T1190",
    what: "Toggle AI opt-out on a test scan, then verify persistence: reload the report, re-fetch via API, and check a second session. A toggle that doesn't stick is the finding.",
  },
  {
    id: "SS-078", category: "logic", name: "Opt-out redaction verification",
    brief: "Opted-out scan — evidence snippets, URLs, headers truly absent from AI-visible fields?",
    owasp: "WSTG-ATHZ / privacy", attackId: "T1190",
    what: "Enable AI opt-out, then forensically verify the report output: no evidence snippets, target URLs, response headers, or identifiers in any AI-visible field. Opt-out that doesn't redact is the finding.",
  },
  {
    id: "SS-079", category: "functionality", name: "Opt-out bypass via alternate path",
    brief: "Export/share/MCP paths — do they honor the opt-out redaction?",
    owasp: "WSTG-ATHZ / privacy", attackId: "T1190",
    what: "With opt-out enabled, pull the same scan through every alternate path: exports, share links, MCP get_report. Any path serving unredacted content the main view redacts is the finding.",
  },
  {
    id: "SS-080", category: "logic", name: "Opt-out toggle on another account's scan",
    brief: "Flipping someone else's opt-out — authorization on the privacy control?",
    owasp: "WSTG-ATHZ-04", attackId: "T1190",
    what: "Attempt to toggle AI opt-out on another owned test account's scan. Privacy controls need the same authorization boundary as the data — cross-account toggling is the finding.",
    needs: "Second test account owned by the operator.",
  },
  // ============================================ RATE LIMITS (mixed)
  {
    id: "SS-081", category: "logic", name: "Intake limiter shape mapping",
    brief: "429 mapping — is the intake limit per-account, per-IP, or per-namespace?",
    owasp: "OWASP API4:2023", attackId: "T1499",
    what: "Probe the namespaced intake rate limit with a handful of requests: observe 429 shape, Retry-After, and whether the bucket is per-account, per-IP, or per-namespace. Mapping the limiter's shape — never stressing it.",
    blackNote: "Handful of probes only — this maps the limiter, it does not stress it.",
  },
  {
    id: "SS-082", category: "logic", name: "X-Forwarded-For rotation vs intake limiter",
    brief: "Rotating XFF — does the limiter key on a spoofable header?",
    owasp: "OWASP API4:2023", attackId: "T1499",
    what: "Replay intake requests with rotated X-Forwarded-For / X-Real-IP values (a few probes). If the limit resets per header value, the limiter keys on spoofable input — the finding. Never a real bypass campaign.",
  },
  {
    id: "SS-083", category: "logic", name: "Share limiter bypass mapping",
    brief: "Same limiter analysis on the share namespace — consistent enforcement?",
    owasp: "OWASP API4:2023", attackId: "T1499",
    what: "Map the share-namespace limiter the same way: shape, keying, and whether its strictness matches the intake limiter. Inconsistent enforcement between namespaces is the finding.",
    blackNote: "Handful of probes only.",
  },
  {
    id: "SS-084", category: "validation", name: "429 response differential",
    brief: "Does the 429 body leak limiter configuration?",
    owasp: "WSTG-ERRH-01", attackId: "T1592.002",
    what: "Inspect 429 responses for leaked configuration: limit values, window sizes, bucket keys, internal identifiers. Informative rate-limit responses are the finding.",
  },
  {
    id: "SS-085", category: "logic", name: "Limiter reset behavior",
    brief: "Window reset — fixed or sliding? predictable reset abused?",
    owasp: "OWASP API4:2023", attackId: "T1499",
    what: "Observe limiter reset timing across a few windows: fixed vs sliding, and whether the reset moment is predictable enough to schedule around. Observation only — never engineered into sustained over-limit traffic.",
  },
  // ============================================ AUTH / SESSION (mixed)
  {
    id: "SS-086", category: "logic", name: "Session fixation",
    brief: "Attacker-set session ID surviving login — fixation possible?",
    owasp: "WSTG-SESS-03", attackId: "T1190",
    what: "If cookie auth exists: set a session cookie pre-login, complete login with a test account, and check whether the pre-login ID survived. Survival is the finding. Test accounts only.",
  },
  {
    id: "SS-087", category: "logic", name: "Password-reset token reuse and expiry",
    brief: "Reset token replayed, expired, tampered — single-use and time-bound?",
    owasp: "WSTG-ATHN-04", attackId: "T1556",
    what: "Trigger reset for an operator-owned test account, then: reuse the token twice, use it after expiry, and tamper with its structure. Tokens must be single-use and time-bound. Never trigger emails to real users.",
    needs: "Test account with operator-controlled email.",
  },
  {
    id: "SS-088", category: "logic", name: "Reset for another identifier → enumeration",
    brief: "Reset requested for other emails — existence oracle in the response?",
    owasp: "WSTG-ATHN-04", attackId: "T1087",
    what: "Request resets for existent vs nonexistent operator-controlled identifiers and compare responses/timing. A differential is an account-enumeration oracle — the finding, not a harvest. Never target real users.",
    needs: "Operator-controlled test identifiers.",
    blackNote: "Minimal probes; stop at the first differential.",
  },
  {
    id: "SS-089", category: "functionality", name: "Login enumeration differential",
    brief: "Valid vs invalid username — timing or message differential?",
    owasp: "WSTG-ATHN-02", attackId: "T1087",
    what: "Compare login responses for valid vs invalid test usernames: messages, timing, and status codes. Any differential is the finding. Test accounts only, handful of probes.",
    blackNote: "Minimal probes; stop at the first differential.",
  },
  {
    id: "SS-090", category: "logic", name: "Change-email without re-authentication",
    brief: "Account email changed on session alone — re-auth required?",
    owasp: "WSTG-ATHN", attackId: "T1556",
    what: "Change the account email of a test account using only the session (no password re-entry). Sensitive account changes must demand re-authentication — its absence is the finding.",
  },
  {
    id: "SS-091", category: "logic", name: "Logout invalidates the session",
    brief: "Post-logout session replay — truly dead server-side?",
    owasp: "WSTG-SESS-06", attackId: "T1190",
    what: "Log out a test account, then replay the old session cookie/token against authenticated endpoints. The session must die server-side — any post-logout acceptance is the finding.",
  },
  {
    id: "SS-092", category: "validation", name: "Cookie flags observation",
    brief: "HttpOnly/Secure/SameSite on session cookies — set correctly?",
    owasp: "WSTG-SESS-02", attackId: "T1592.002",
    what: "Inspect session cookies passively: HttpOnly, Secure, SameSite, Path, and Domain scope. Missing flags are reported as hardening findings — observation only, no exploitation.",
  },
  {
    id: "SS-093", category: "functionality", name: "Concurrent session handling",
    brief: "Second login kills the first? password change kills all sessions?",
    owasp: "WSTG-SESS", attackId: "T1190",
    what: "Log in twice with a test account and check whether the first session survives; then change the password and check whether all sessions die. Stale sessions surviving credential change is the finding.",
  },
  {
    id: "SS-094", category: "logic", name: "Password-change logic flaws",
    brief: "Change without old password, weak new password accepted?",
    owasp: "WSTG-ATHN", attackId: "T1556",
    what: "Attempt password change without the current password, with a weak new password, and with the username as the password. Each missing check is the finding. Test account only.",
  },
  // ============================================ API SURFACE (mixed)
  {
    id: "SS-095", category: "functionality", name: "Web→API parity replay",
    brief: "Every web flow replayed via the API — same authz, same validation?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Replay intake, status, report, share, and listing flows directly against the REST API. The API must enforce everything the web UI enforces — any API path weaker than its web twin is the finding.",
  },
  {
    id: "SS-096", category: "validation", name: "API accepts what the web form rejects",
    brief: "Client-side-only validation — does the server re-validate?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Submit directly what the UI forbids: disabled aggressive-tier toggle, JS URL checks, maxlength attributes. The question is always whether the server re-validates — bypass is the finding.",
  },
  {
    id: "SS-097", category: "functionality", name: "API versioning gaps",
    brief: "Old API versions / legacy paths — still live with old flaws?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Probe for versioned API paths (/v1, /api/v1, legacy routes) and replay attacks against them. An old version with weaker checks than current is the finding.",
  },
  {
    id: "SS-098", category: "validation", name: "API error verbosity vs web",
    brief: "JSON errors with stack traces the HTML view hides?",
    owasp: "WSTG-ERRH-01", attackId: "T1592.002",
    what: "Compare error verbosity between the web UI and the API for identical bad input. Stack traces, SQL fragments, or internal paths in JSON errors are the finding.",
  },
  {
    id: "SS-099", category: "functionality", name: "API authentication edge cases",
    brief: "Every API endpoint without a token — uniformly 401?",
    owasp: "OWASP API2:2023", attackId: "T1190",
    what: "Hit every discovered API endpoint with no credentials, malformed tokens, and expired-shaped tokens. Any endpoint that behaves differently unauthenticated is the finding.",
  },
  // ============================================ TLS / HEADERS / CORS (mixed)
  {
    id: "SS-100", category: "validation", name: "Security headers observation",
    brief: "HSTS, CSP, X-Frame-Options, Referrer-Policy — present and strict?",
    owasp: "WSTG-CONF", attackId: "T1592.002",
    what: "Passively record security headers on the app, report, and share pages: HSTS (includeSubDomains, preload), CSP, X-Frame-Options, Referrer-Policy, Permissions-Policy. Missing/weak headers are hardening findings — observation only.",
  },
  {
    id: "SS-101", category: "functionality", name: "CORS reflected Origin with credentials",
    brief: "Attacker Origin reflected with Access-Control-Allow-Credentials?",
    owasp: "WSTG-CONF", attackId: "T1190",
    what: "Send canary Origin values (evil-canary, null, subdomain tricks) and check reflection plus credentials flag. Reflected origin with credentials=true is the finding. Benign canary origins only.",
  },
  {
    id: "SS-102", category: "functionality", name: "Open redirect via next/return params",
    brief: "next=/\\evil-canary — redirect parameters validated?",
    owasp: "WSTG-CLNT-04", attackId: "T1190",
    what: "Probe redirect parameters (next, return, redirect, continue) with canary-external targets, protocol-relative URLs, and backslash tricks. Open redirect to a canary host is the finding — canary only, never a real external site.",
  },
  {
    id: "SS-103", category: "validation", name: "Host header injection effects",
    brief: "Poisoned Host — cache poisoning, reset-link poisoning, or clean ignore?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Send requests with poisoned Host / X-Forwarded-Host values (canary hostnames) and observe: password-reset links, cached responses, and absolute URLs generated. Any reflection of the poisoned host is the finding.",
  },
  // ============================================ ERROR HANDLERS (mixed)
  {
    id: "SS-104", category: "validation", name: "404/500 verbosity",
    brief: "Error pages with stack traces or framework fingerprints?",
    owasp: "WSTG-ERRH-01", attackId: "T1592.002",
    what: "Trigger 404s and 500s across the app (bad paths, bad IDs) and harvest verbosity: stack traces, framework versions, SQL fragments. Verbose errors are the finding.",
  },
  {
    id: "SS-105", category: "functionality", name: "Error-based enumeration",
    brief: "Valid vs invalid UUID timing/message differentials — oracle?",
    owasp: "WSTG-ATHN", attackId: "T1087",
    what: "Compare timing and messages for valid-format vs invalid-format vs nonexistent scan IDs on own-account endpoints. A differential is an enumeration oracle — the finding, not a harvest.",
    blackNote: "Minimal probes; stop at the first differential.",
  },
  // ============================================ SCANNER EFFICACY (logic)
  // The red team adversarially validates the scanner itself: canary targets
  // with KNOWN planted flaws verify SecScan detects what it claims.
  // Non-destructive, canary targets only — detection-validation, not abuse.
  {
    id: "SS-106", category: "logic", name: "Efficacy: planted reflected XSS detected",
    brief: "Canary with known reflected XSS — does the scan report it?",
    owasp: "WSTG-INPV-02", attackId: "T1190",
    what: "Scan a canary target with a deliberately planted reflected XSS and verify the scan reports it with the right classification. A miss is a detection-gap finding — the scanner's core promise under test.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  {
    id: "SS-107", category: "logic", name: "Efficacy: planted SQLi error detected",
    brief: "Canary with known SQLi error surface — reported?",
    owasp: "WSTG-INPV-05", attackId: "T1190",
    what: "Scan a canary target with a planted SQL error surface and verify detection. A miss is a detection-gap finding.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  {
    id: "SS-108", category: "logic", name: "Efficacy: missing security headers reported",
    brief: "Canary stripped of security headers — flagged?",
    owasp: "WSTG-CONF", attackId: "T1190",
    what: "Scan a canary target with deliberately missing security headers and verify the report flags each one. Missing flags are detection gaps.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  {
    id: "SS-109", category: "logic", name: "Efficacy: exposed .git reported",
    brief: "Canary with exposed .git — information-disclosure finding raised?",
    owasp: "WSTG-INFO", attackId: "T1592.002",
    what: "Scan a canary target exposing a fake .git directory and verify the scanner reports it. A miss is a detection-gap finding.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  {
    id: "SS-110", category: "logic", name: "Efficacy: weak TLS reported",
    brief: "Canary with TLS 1.0/1.1 — flagged in the report?",
    owasp: "WSTG-CRYP", attackId: "T1190",
    what: "Scan a canary target serving weak TLS and verify the report flags it. A miss is a detection-gap finding.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  {
    id: "SS-111", category: "logic", name: "Efficacy: open redirect reported",
    brief: "Canary with a deliberate open redirect — caught?",
    owasp: "WSTG-CLNT-04", attackId: "T1190",
    what: "Scan a canary target with a planted open redirect and verify detection. A miss is a detection-gap finding.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  {
    id: "SS-112", category: "logic", name: "Efficacy: verbose errors reported",
    brief: "Canary with stack-trace errors — information-disclosure finding?",
    owasp: "WSTG-ERRH-01", attackId: "T1190",
    what: "Scan a canary target emitting verbose errors and verify the scanner flags information disclosure. A miss is a detection-gap finding.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  {
    id: "SS-113", category: "logic", name: "Efficacy: known-vulnerable JS library reported",
    brief: "Canary loading a known-vuln library version — flagged?",
    owasp: "WSTG-INFO / SCA", attackId: "T1190",
    what: "Scan a canary target loading a deliberately outdated JS library and verify the report flags it. A miss is a detection-gap finding.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  {
    id: "SS-114", category: "logic", name: "Efficacy: clean target precision",
    brief: "Hardened canary with no flaws — any false positives?",
    owasp: "Detection precision", attackId: "T1190",
    what: "Scan a hardened canary target with no planted flaws. Every finding on a clean target is a false positive — precision is half the scanner's promise, and false positives erode trust exactly like misses do.",
    needs: "Hardened canary target under operator control.",
  },
  {
    id: "SS-115", category: "logic", name: "Efficacy: severity calibration",
    brief: "Planted critical flaw — graded critical, not low?",
    owasp: "Detection calibration", attackId: "T1190",
    what: "Plant flaws of known severity (one critical, one low) on a canary target and verify the grades match. Misgraded severity is a calibration finding — a critical graded 'low' is as dangerous as a miss.",
    needs: "Canary target with planted flaws, under operator control.",
  },
  // ============================================ CROSS-CUTTING (mixed)
  {
    id: "SS-116", category: "functionality", name: "Cache poisoning via forwarded host",
    brief: "X-Forwarded-Host on report pages — poisoned cache served to others?",
    owasp: "WSTG-INPV", attackId: "T1190",
    what: "Send report-page requests with canary X-Forwarded-Host values and check whether the poisoned response gets cached and served to a clean request. Cache poisoning is the finding — canary hostnames only.",
  },
  {
    id: "SS-117", category: "logic", name: "Host-header password-reset poisoning",
    brief: "Poisoned Host in reset flow — reset link points at attacker host?",
    owasp: "WSTG-ATHN-04", attackId: "T1190",
    what: "Trigger a reset for an operator-owned test account with a poisoned Host header and inspect where the reset link points. A link pointing at the canary host is the finding. Never target real users.",
    needs: "Test account with operator-controlled email.",
  },
  {
    id: "SS-118", category: "logic", name: "Free-tier quota enforcement",
    brief: "Free scans exhausted — is the (N+1)th scan refused?",
    owasp: "WSTG-BUSL-01", attackId: "T1190",
    what: "Exhaust the free-tier scan quota on a test account and attempt one more scan. The refusal must be clean — a granted over-quota scan is the finding. Operator-owned credits only.",
  },
  {
    id: "SS-119", category: "logic", name: "Credit parity across intake paths",
    brief: "Web, API, and MCP intake — identical credit accounting?",
    owasp: "WSTG-BUSL-01", attackId: "T1190",
    what: "Create one scan through each intake path (web, API, MCP) and compare credit deduction. Any path that deducts differently — especially one that deducts nothing — is the finding.",
  },
  {
    id: "SS-120", category: "validation", name: "CSRF on state-changing endpoints",
    brief: "Share-create and intake without CSRF tokens — cross-site forgery?",
    owasp: "WSTG-SESS-05", attackId: "T1190",
    what: "Replay share-creation and scan-intake as cross-origin form posts without CSRF tokens (test account). Missing or non-validated tokens on state-changing endpoints is the finding.",
  },
];

export const SECSCAN_PROFILE: TargetProfile = {
  id: "secscan",
  name: "SecScan — scanner web app",
  baseUrl: "https://secscan.us",
  kind: "webapp",
  authModel: "DNS TXT ownership gate (_secscan-challenge.<domain>, server-authoritative) + session auth for reports/shares; scan intake rate-limited per namespace.",
  scopeNotes: "In-scope: secscan.us webapp surface (intake, scan lifecycle, reports, share links). Out-of-scope: anything not on the scoped host; no emails to real users; no scan/report deletion.",
  battery: SECSCAN_BATTERY,
};
