/**
 * In-memory registries for the UI server (v0.22.0).
 *
 * Engagements launched through the UI are tracked here with their abort
 * handles (kill switch). Historical engagements are listed from the
 * engagements dir on disk — the UI works even for runs started by the CLI.
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";
import { randomBytes } from "node:crypto";
import type { StoredEngagement, UiJob } from "./types.js";
import { readState, type LiveState } from "../events.js";

/** Same env convention as resolveConfig: REDTEAM_HOME or cwd. */
export function defaultEngagementsDir(): string {
  const home = process.env["REDTEAM_HOME"];
  return home ? join(home, "engagements", "live") : join(process.cwd(), "engagements", "live");
}

/** Engagement IDs are generated by the runner — accept only the safe shape. */
export function isSafeEngagementId(id: string): boolean {
  return /^[A-Za-z0-9][A-Za-z0-9_-]{0,120}$/.test(id);
}

/** Resolve an engagement dir, refusing path traversal. */
export function engagementDir(base: string, id: string): string | undefined {
  if (!isSafeEngagementId(id)) return undefined;
  const dir = resolve(base, id);
  if (!dir.startsWith(resolve(base) + sep) && dir !== resolve(base)) return undefined;
  if (!existsSync(join(dir, "state.json"))) return undefined;
  return dir;
}

export function generateEngagementId(): string {
  return `eng-${new Date().toISOString().slice(0, 10)}-${randomBytes(2).toString("hex")}`;
}

export interface EngagementSummary {
  id: string;
  target: string;
  mode: string;
  status: string;
  phase: string;
  findings: number;
  eventCount: number;
  startedAt: string;
  updatedAt: string;
  live: boolean;
}

function toSummary(id: string, state: LiveState, live: boolean): EngagementSummary {
  return {
    id,
    target: state.target,
    mode: state.mode,
    status: state.status,
    phase: state.phase,
    findings: state.findings.length,
    eventCount: state.eventCount,
    startedAt: state.startedAt,
    updatedAt: state.updatedAt,
    live: live,
  };
}

export class UiStore {
  private live = new Map<string, StoredEngagement>();
  private jobs = new Map<string, UiJob>();
  readonly engagementsDir: string;

  constructor(engagementsDir?: string) {
    this.engagementsDir = engagementsDir ?? defaultEngagementsDir();
  }

  register(e: StoredEngagement): void {
    this.live.set(e.id, e);
  }

  get(id: string): StoredEngagement | undefined {
    return this.live.get(id);
  }

  setAbort(id: string, abort: (reason: string) => void): void {
    const e = this.live.get(id);
    if (e) {
      e.abort = abort;
      e.status = "running";
    }
  }

  complete(id: string): void {
    const e = this.live.get(id);
    if (e) {
      e.abort = undefined;
      const st = readState(e.dir);
      e.status = st?.status ?? "complete";
    }
  }

  fail(id: string, err: unknown): void {
    const e = this.live.get(id);
    if (e) {
      e.abort = undefined;
      e.status = "halted";
      e.error = err instanceof Error ? err.message : String(err);
    }
  }

  /** All engagements: live-tracked first, then history from disk. */
  list(): EngagementSummary[] {
    const out: EngagementSummary[] = [];
    const seen = new Set<string>();
    for (const [id, e] of this.live) {
      const st = readState(e.dir);
      if (st) {
        out.push(toSummary(id, st, true));
        seen.add(id);
      }
    }
    if (existsSync(this.engagementsDir)) {
      const dirs = readdirSync(this.engagementsDir, { withFileTypes: true })
        .filter((d) => d.isDirectory() && isSafeEngagementId(d.name) && !seen.has(d.name))
        .map((d) => d.name);
      for (const id of dirs) {
        const st = readState(join(this.engagementsDir, id));
        if (st) out.push(toSummary(id, st, false));
      }
    }
    out.sort((a, b) => (a.startedAt < b.startedAt ? 1 : -1));
    return out;
  }

  // -- background jobs (reverify-execute, watch trigger) ---------------------

  createJob(kind: UiJob["kind"]): UiJob {
    const job: UiJob = {
      id: `job-${randomBytes(4).toString("hex")}`,
      kind,
      status: "running",
      startedAt: new Date().toISOString(),
    };
    this.jobs.set(job.id, job);
    return job;
  }

  finishJob(id: string, result: unknown): void {
    const j = this.jobs.get(id);
    if (j) {
      j.status = "done";
      j.finishedAt = new Date().toISOString();
      j.result = result;
    }
  }

  failJob(id: string, error: unknown): void {
    const j = this.jobs.get(id);
    if (j) {
      j.status = "failed";
      j.finishedAt = new Date().toISOString();
      j.error = error instanceof Error ? error.message : String(error);
    }
  }

  getJob(id: string): UiJob | undefined {
    return this.jobs.get(id);
  }

  /** Read a JSON artifact from an engagement dir (null when absent). */
  readJsonArtifact(id: string, name: string): unknown | null {
    const dir = engagementDir(this.engagementsDir, id);
    if (!dir) return null;
    const p = join(dir, name);
    if (!existsSync(p)) return null;
    try {
      return JSON.parse(readFileSync(p, "utf8"));
    } catch {
      return null;
    }
  }

  /** Read a markdown artifact from an engagement dir (null when absent). */
  readTextArtifact(id: string, name: string): string | null {
    const dir = engagementDir(this.engagementsDir, id);
    if (!dir) return null;
    const p = join(dir, name);
    if (!existsSync(p)) return null;
    try {
      return readFileSync(p, "utf8");
    } catch {
      return null;
    }
  }

  /** List files in a subdir of the engagement dir (e.g. poc/). */
  listSubdir(id: string, sub: string): string[] {
    const dir = engagementDir(this.engagementsDir, id);
    if (!dir || !/^[A-Za-z0-9_-]+$/.test(sub)) return [];
    const p = join(dir, sub);
    if (!existsSync(p)) return [];
    try {
      return readdirSync(p).filter((f) => f.endsWith(".json")).sort();
    } catch {
      return [];
    }
  }
}
